.github/workflows/deploy.yml
Gemfile.lock

* reformat file
* use DavidS/jekyll-deploy@master
* Update Gemfile.lock to modern bundler
* add caching

Update deploy workflow

---

_data/tools.yml

This is based on repositories we're responsible for.

Add our tools

---

_posts/2020-04-24-status-update.md

* Add more DSC details
* fix a bunch of typos
* formatting fixes
* cleaning up links

Copy-edits and additional points

---

_posts/2020-05-01-status-update.md

(post) - 01/05/2020 IAC Blog Post

---

_posts/2020-07-03-apache-mod-test-improvements.md

**TODO before merging:**
**TODO after merging:**

(post) Apache MOD test filtering functionality

---

_posts/2020-08-28-status-update.md

Status update 2020-08-28

---

bin/blog_tools/Gemfile
bin/blog_tools/README.md
bin/blog_tools/blog_template/status-update-template.md.erb
bin/blog_tools/bootstrap_blog.rb
bin/blog_tools/lib/common.rb
bin/blog_tools/lib/community_prs.rb
bin/blog_tools/lib/modules_released.rb
bin/blog_tools/lib/octokit_util.rb

Automate the stuff that can be automated for the weekly blog status updates:
- Gathering community contributions for the past week
- Gathering modules released for the past week

Bootstrap the weekly status blog!

---

_lifeofinternatpuppet/post_5.md

This is an update of week 5 at Puppet for Placement Year.

Week 5 Blog Post

---

bin/remote_acceptance_test_runner/Gemfile
bin/remote_acceptance_test_runner/README.md
bin/remote_acceptance_test_runner/remote_runner.rb

This is a script that will allow you to run Litmus acceptance tests
from an Ubuntu 18.04 host provisioned via ABS.

Remote Runner script for Litmus acceptance tests

---

_lifeofinternatpuppet/post_7_and_8

Please check the final changes Ciaran or anyone who is free now

Blog updates for weeks 7 & 8

---

_lifeofinternatpuppet/post_12.md

This a blog update for Week 12

(MAINT) Blog Update for Week 12

---

_posts/2020-11-20-status-update.md

Just a quick fix to two of the links

(maint) - 2020-11-20-status-update.md doc fix

---

_posts/2020-11-20-status-update.md

Update to iclude rference to Disha's newest post.

(maint) - 2020-11-20-status-update.md life_of_intern update

---

_posts/2020-11-23-puppetize-digital.md

Co-Authored-By: Ciaran McCrisken <ciaran.mccrisken@puppet.com>

integrate ciaran's fixes for Puppetize Digital post

---

_lifeofinternatpuppet/post_15.md

(Blog) Update for Week 15

---

_lifeofinternatpuppet/post_16.md

This is the new PR, everything looks good

(blog) Week 16 blog post update

---

_posts/2020-12-18-status-update.md

(maint) Small update

---

_posts/2021-01-08-status-update.md

This is a re-run of bootstrap_blog.rb with the relevant changes cherry-picked

Fix links on releases

---

_posts/2021-01-29-status-update.md

(blog) 2021-01-29 status update

---

_posts/2021-01-26-converting-puppetized-dsc-modules.md

This Blog post addresses https://github.com/puppetlabs/Puppet.Dsc/issues/90

(GH-90) Converting to use new DSC modules Blog Post

---

_posts/2021-01-20-reaching-out.md

This should make it stand out better in the list.

Remove date from "Reaching out" post

---

bin/blog_tools/lib/community_prs.rb

(maint) Discard PRs/comment author from github-actions[bot], CLAassistant

---

_lifeofinternatpuppet/post_17.md

1. Added puppetlabs-mysql new version release (v10.9.1)
2. Learnt how to solve merge conflicts in PRs
3. Combined commits messages into one PR by creating a new one
4. 2 Separate PRs with individual commit messages for Week 17 Blog Update were closed.

(Blog) Updating Content for Week 17

---

README.md
_docs/demos.md

Removal of any offensive or inappropriate terminology from the code base.

(IAC-1464) - Removal of Inappropriate Terminology

---

_posts/2021-04-02-status-update.md
bin/blog_tools/lib/octokit_util.rb

... and a small fix at bin/blog_tools/lib/octokit_util.rb

2021-04-02 blogpost

---

_lifeofinternatpuppet/post_19.md

1. Adding descriptive PRs link names
2. Grammar Fix, added the word merged in a paragraph on Line 28

(blog) (maint) Week 19 Blog Update Minor Fixes

---

_posts/2021-04-02-status-update.md

This title has no content under it therefore is not necessary.

(maint) Remove unnecessary title

---

_docs/life_of_intern.md
_lifeofinternatpuppet/post_30.md

1.  Week 30 Blog Update Created and a Link to the Week 30 Blog Post Added in the life_of_intern.md file

(blog) Week 30 Update

---

_docs/reviewing-pull-requests.md

This document outlines the role of a reviewer when reviewing a PR for one of our supported modules.

(DOC) - Role of a reviewer

---

_docs/life_of_intern.md
_lifeofinternatpuppet/post_1.md
_lifeofinternatpuppet/post_10.md
_lifeofinternatpuppet/post_2.md
_lifeofinternatpuppet/post_3.md
_lifeofinternatpuppet/post_34.md
_lifeofinternatpuppet/post_4.md
_lifeofinternatpuppet/post_5.md
_lifeofinternatpuppet/post_6.md
_lifeofinternatpuppet/post_7.md
_lifeofinternatpuppet/post_8.md

This PR included the following changes
1.  Fixed formatting of old blog posts:- post_1, post_2, post_3, post_4, post_5, post_6, post_7, post_8 and post_10.
2. Renamed the file post_7_and_8.md to post_7.md and post_8.md respectively.
3. Week 34 blog update added too.
4. The life_of_intern.md file was updated. New blog entries added:- Week 8 and Week 34. Week 7 hyperlink was updated too.

(blog) Fix formatting of old blog posts and week 34 blog update added

---

_posts/2021-05-21-status-update.md

(blog) Status Update 2021-05-21

---

_lifeofinternatpuppet/post_41.md

Added the --- at the start of post_41.md file to fix the 404 error discovered in the previous PR. Check the link here:- https://github.com/puppetlabs/iac/pull/281

(blog) (bug) Fixing the 404 Error on this Blog Update

---

_lifeofinternatpuppet/post_42.md

Check the link to the merged PR from last week for reference purposes 
https://github.com/puppetlabs/iac/pull/285

(blog) More content added in Week 42 Blog Update 

---

_lifeofinternatpuppet/post_3.md
_lifeofinternatpuppet/post_7.md

Full stops added in week_3 blog post
break links removed from week_7 blog post
spelling error fixed in week_7 blog post

(blog) Formatting corrections in week_3 and week_7 blog posts

---

_lifeofinternatpuppet/post_45.md

Changing the month from August to July

(blog) Week 45 Blog Update Fix

---

bin/blog_tools/lib/community_prs.rb

(GH-257) Exclude "dependabot" author from PR credits

---

.github/workflows/deploy.yml
.github/workflows/test.yml

This reverts commit fc1005c5eb3365b9da3ee2cd648c63601cd09b4d.
Closes: #305

Revert "(GH-305) Remove gem cache steps from deploy and test workflows"

---

LICENSE

This PR adds an Apache 2.0 license as this seems to be what is used in other places in the organisation.
Closes #332

(MAINT) Add a license file

---

README.md
_includes/header.html

This PR adds a banner that is displayed on every page. It's purpose is to notify the user that the site has moved.

(MAINT) Add global banner
